##本地（开发环境）配置
#spring:
#  redis:
#    #数据库索引
#    database: 0
##    host: 10.19.132.217
##    port: 6379
#    password:
#    #连接超时时间
#    timeout: 10000
#    cluster:
#      nodes: 10.19.132.217:7000,10.19.132.217:7001,10.19.132.217:7002
#      #在群集中执行命令时要遵循的最大重定向数目（不使用则不用开启）
##      max-redirects:
##    jedis:
##      pool:
##        #最大连接数
##        max-active: 10
##        #最大阻塞等待时间(负数表示没限制)
##        max-wait: -1
##        #最大空闲
##        max-idle: 10
##        #最小空闲
##        min-idle: 0
#    lettuce:
#        pool:
#          max-active: 20
#          max-wait: 300
#          max-idle: 16
#          min-idle: 8


server:
  port: 8080
redis:
#  clusterHost: 10.19.132.217,10.19.132.217,10.19.132.217
#  clusterPort: 7000,7001,7002
  redisHost: 127.0.0.1
  redisPort: 6379
  redisPassword:
  expireTime: 3600
  minIdle: 0
  maxTotal: 10